// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public enum FitnessEquipment: String, EnumType {
  case barbells = "Barbells"
  case weightPlates = "WeightPlates"
  case dumbbells = "Dumbbells"
  case squatRacks = "SquatRacks"
  case flatInclineDeclineBenches = "FlatInclineDeclineBenches"
  case smithMachines = "SmithMachines"
  case cableMachines = "CableMachines"
  case legPressMachines = "LegPressMachines"
  case latPullDownMachines = "LatPullDownMachines"
  case seatedRowMachines = "SeatedRowMachines"
  case legExtensionMachines = "LegExtensionMachines"
  case legCurlMachines = "LegCurlMachines"
  case hackSquatMachines = "HackSquatMachines"
  case calfRaiseMachines = "CalfRaiseMachines"
  case shoulderPressMachines = "ShoulderPressMachines"
  case chestPressMachines = "ChestPressMachines"
  case assistedPullUpDipMachines = "AssistedPullUpDipMachines"
  case preacherCurlBenches = "PreacherCurlBenches"
  case hyperextensionBenches = "HyperextensionBenches"
  case kettlebells = "Kettlebells"
  case medicineBalls = "MedicineBalls"
  case resistanceBands = "ResistanceBands"
  case tRXSuspensionTrainers = "TRXSuspensionTrainers"
  case battleRopes = "BattleRopes"
  case plyometricBoxes = "PlyometricBoxes"
  case multiStationGyms = "MultiStationGyms"
  case abdominalCrunchMachines = "AbdominalCrunchMachines"
  case pecDeckMachines = "PecDeckMachines"
  case hammerStrengthMachines = "HammerStrengthMachines"
  case gluteHamDevelopersGHD = "GluteHamDevelopersGHD"
  case sledsProwlers = "SledsProwlers"
  case farmersWalkHandles = "FarmersWalkHandles"
  case landmineAttachments = "LandmineAttachments"
  case trapBarsHexBars = "TrapBarsHexBars"
  case eZCurlBars = "EZCurlBars"
  case olympicLiftingPlatforms = "OlympicLiftingPlatforms"
  case bumperPlates = "BumperPlates"
  case stabilityBallsExerciseBalls = "StabilityBallsExerciseBalls"
  case bosuBalls = "BosuBalls"
  case medicineBallRebounders = "MedicineBallRebounders"
  case gripStrengtheners = "GripStrengtheners"
  case pullUpBars = "PullUpBars"
  case dipStations = "DipStations"
  case tBarRowMachines = "TBarRowMachines"
  case seatedCalfRaiseMachines = "SeatedCalfRaiseMachines"
  case abRollers = "AbRollers"
  case reverseHyperMachines = "ReverseHyperMachines"
  case functionalTrainerMachines = "FunctionalTrainerMachines"
  case seatedLegPressMachines = "SeatedLegPressMachines"
}
